FROM ubuntu:24.04
ARG PI_NODE_VERSION
ENV PI_NODE_VERSION=${PI_NODE_VERSION:-*}
ARG PI_RPC_VERSION
ENV PI_RPC_VERSION=${PI_RPC_VERSION:-*}

ENV PI_NODE_BINARY_PATH=/usr/bin/pi-node
ENV DEBIAN_FRONTEND=noninteractive

# ca-certificates are required to make tls connections
RUN apt-get update && apt-get install -y --no-install-recommends \
    ca-certificates \
    curl \
    jq \
    wget \
    gnupg \
    && apt-get clean \
    && rm -rf /var/lib/apt/lists/*

RUN mkdir -p /etc/apt/keyrings && curl -sSL https://apt.stellar.org/SDF.asc | gpg --dearmor -o /etc/apt/keyrings/SDF.gpg && \
    echo "deb [signed-by=/etc/apt/keyrings/SDF.gpg] https://apt.stellar.org noble stable" >/etc/apt/sources.list.d/SDF.list && \
    echo "deb [signed-by=/etc/apt/keyrings/SDF.gpg] https://apt.stellar.org noble testing" >/etc/apt/sources.list.d/SDF-testing.list && \
    echo "deb [signed-by=/etc/apt/keyrings/SDF.gpg] https://apt.stellar.org noble unstable" >/etc/apt/sources.list.d/SDF-unstable.list

RUN apt-get update && \
    apt-get install -y --no-install-recommends stellar-core=${PI_NODE_VERSION} && \
    ln -s /usr/bin/stellar-core /usr/bin/pi-node && \
    apt-get clean \
    && rm -rf /var/lib/apt/lists/*

# Note: Assuming the pi-rpc binary is installed as stellar-rpc in the package for now
# If you are building manually, use the other Dockerfile.
ENTRYPOINT ["/usr/bin/pi-rpc"]
